#!/bin/sh

fastboot flash partition gpt_both0.bin
fastboot flash hyp hyp.mbn
fastboot flash rpm rpm.mbn
fastboot flash sbl1 sbl1.mbn
fastboot flash tz tz.mbn
[ -e sec.dat ] && fastboot flash sec sec.dat
fastboot flash cdt sbc_1.0_8016.bin
fastboot flash aboot emmc_appsboot.mbn

fastboot erase boot_a
fastboot erase writable

fastboot flash boot_a boot-db410c.img
fastboot flash boot_r boot-db410c.img
fastboot flash snapbootsel snapbootsel.bin
fastboot flash snapbootselbak snapbootsel.bin
fastboot flash seed seed.img
